Add switches for Quiet, Turbo and Eco mode
jhthorsen/homebridge-tasmota-aircon-http pull request #2
Opened 2022-01-13 22:45 UTC by macjl

Please review my code, as I'm not a developper !!

2022-01-14 08:03 UTC, jhthorsen requested changes
Thanks for the contribution!

I think most of the changes makes sense, but I do wonder if there's a bug where I mentioned the indentation. A test in https://github.com/jhthorsen/homebridge-tasmota-aircon-http/blob/main/test/plugin.js could prove that... I can write the test for you, but I need to know the intention first.

Further more, all the nitpicking from my side is simply because "git blame" will last longer if the code is sorted properly. It also makes i a lot easier for me to maintain it later on when thinks are in a predictable order.

2022-01-14 08:03 UTC, jhthorsen commented on config.schema.json
> +        "title": "Turbo Switch",
I wonder if this should be changed to "Enable Turbo Switch Homekit service", to make it more descriptive. Same goes for the one below. (Open for other suggestions)

2022-01-16 14:06 UTC, macjl commented
Hello,

Thank you for your feedbacks. I cleaned the code. Tell me if it's OK for you.

Regards,

2022-01-16 14:21 UTC, macjl commented
I avec added a modification, to ensure that the switches aren't set to Off, when an automation put a switch to Off the is already in that state.

2022-01-19 20:07 UTC, macjl commented
Hello,
Do you think everything is clean now? Or did I miss something ?

2022-01-20 01:51 UTC, jhthorsen approved these changes
Looks good. There isn't any cuddled elses in the code, but I won't hold back the PR because of that.
There's also no tests, so I hope it won't break in the future. I'll try to write some once I find some extra time, unless you beat me to it.

2022-01-20 01:52 UTC, merged

2022-01-20 02:00 UTC, jhthorsen commented
I would like to mention you as a author/contributor. If that is ok, then which name do you want me to use? Git log has your email, but I'm not sure how to translate that into your name.

2022-01-20 20:31 UTC, macjl commented
Thank you
I will check the tests this week-end. I don’t know how it works, that’s why I didn’t make anything on this before.
For mentioning my contribution, you can use my real name : Jean-Laurent Girod 

I also have some proposition for other improvements. I will open others issue for that.